[phases.setup]
nixPkgs = ['nodejs', 'chromium']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run postinstall']

[start]
cmd = 'npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
