services:
  - type: web
    name: whatsapp-server
    env: docker
    plan: starter
    healthCheckPath: /health
    buildCommand: docker build -t whatsapp-server .
    startCommand: docker run -p $PORT:10000 -e PORT=$PORT whatsapp-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
    scaling:
      minInstances: 1
      maxInstances: 1
    autoDeploy: true
